
try { hope.foo(); } catch (e) { console.error("An error occurred when calling (hope/foo)"); throw(e); }